### ISSUE TITLE
Create new ways to print Hello, World!

### ISSUE THREAD

**Issue by NachiketaVadera** [NachiketaVadera/100-ways-to-print-HelloWorld-in-java#18]
# Hello, World!

You can use this repository as a part of the Hacktoberfest fest.

## Task

Create new and interesting ways to print hello world in Java.

**Comment by sharmashantanu** [comment]
Can I work on it?

**Comment by NachiketaVadera** [comment]
@sharmashantanu Sure! Fork the project and submit a PR.

**Comment by ParthPali** [comment]
I want to work on this. Can I do it?

**Comment by ParthPali** [comment]
@NachiketaVadera ... I want to work on this. Can you pls assign it to me.

**Comment by NachiketaVadera** [comment]
@ParthPali Hey! You can make a fork and add a new way to print 'Hello, World!'. No need for any assignments.
