### ISSUE TITLE
Find fun ways to print "Hello, World" in Java.

### ISSUE THREAD

**Issue by NachiketaVadera** [NachiketaVadera/100-ways-to-print-HelloWorld-in-java#48]
# Task
The goal is to help people realize Java concepts by using said concepts to print "Hello, World!".

**Make sure that you read the [contribution guidelines](CONTRIBUTING.md) before you submit a PR.**

**Comment by yrahul3910** [comment]
I'd love to do this!

**Comment by NachiketaVadera** [comment]
Sure! Go ahead.

**Comment by WOLFI3654** [comment]
Just wanted to let you know. For some reason the pull request is not counting towards hacktoberfest. It says that the repo is not participating

**Comment by NachiketaVadera** [comment]
@WOLFI3654 No idea what that is about. Thank you for bringing it to my attention. I'll check out what's up with that.

**Comment by NachiketaVadera** [comment]
@WOLFI3654 Got it here:
[Maintainer Update](https://hacktoberfest.digitalocean.com/hacktoberfest-update)

**Comment by NachiketaVadera** [comment]
@WOLFI3654 I've updated the tag. Check again please.

**Comment by WOLFI3654** [comment]
Thank you! It has been registered

**Comment by yrahul3910** [comment]
Submitted a PR!
