### ISSUE TITLE
Find new and ways to print "Hello, World!" in Java

### ISSUE THREAD

**Issue by NachiketaVadera** [NachiketaVadera/100-ways-to-print-HelloWorld-in-java#64]
# Task
The goal is to help people realize Java concepts by using said concepts to print "Hello, World!".

**Make sure that you read the [contribution guidelines](CONTRIBUTING.md) before you submit a PR.**

**Comment by govindraj111** [comment]
@NachiketaVadera Assign this task to me!

**Comment by govindraj111** [comment]
@NachiketaVadera Please review the PR #73

**Comment by govindraj111** [comment]
@NachiketaVadera Please review the PR #74
