### ISSUE TITLE
Search a character in String "Hello World" via Linear/Binary search in Java

### ISSUE THREAD

**Issue by Ashish7129** [NachiketaVadera/100-ways-to-print-HelloWorld-in-java#65]
Hi @NachiketaVadera ,

Can I proceed with this?

**Comment by NachiketaVadera** [comment]
Hey @Ashish7129! Sure, go ahead. Make sure you read the [contribution guidelines](https://github.com/NachiketaVadera/100-ways-to-print-HelloWorld-in-java/blob/master/CONTRIBUTING.md) though.

**Comment by Ashish7129** [comment]
Hi @NachiketaVadera,

I have committed the code and raised the pull request with #69 . Can you please review it?
