### ISSUE TITLE
Create a Java-based UI login (web or native) to only accept "Hello, World" as input.

### ISSUE THREAD

**Issue by NachiketaVadera** [NachiketaVadera/100-ways-to-print-HelloWorld-in-java#71]
# Task
Make a UI application using a Java technology and validate the input to only accept "Hello, World!".

**Make sure you read the [contribution guidelines.](https://github.com/NachiketaVadera/100-ways-to-print-HelloWorld-in-java/blob/master/CONTRIBUTING.md)**

**Comment by ankitbeniwal** [comment]
I am interested to work on this.

**Comment by NachiketaVadera** [comment]
@ankitbeniwal Sure! Go ahead.

**Comment by dan-r95** [comment]
I would like to do something similar :)
