### ISSUE TITLE
print hello world by making an API call to a custom endpoint

### ISSUE THREAD

**Issue by NachiketaVadera** [NachiketaVadera/100-ways-to-print-HelloWorld-in-java#91]
# Print Hello, World!

That's what's the repository about! For this attempt, you have to create a custom endpoint that server the required 'Hello, World!' string. You can use AWS or some other provider to achieve this. Subsequently, write a Java program to consume that endpoint.

**Comment by shreyavi** [comment]
@NachiketaVadera I created a PR for this issue here https://github.com/NachiketaVadera/100-ways-to-print-HelloWorld-in-java/pull/94
Please take a look, thanks!
